
# Problem 2 -------------------------------------------------------------


# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
  
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

fib_even_sum <- function( limit ) {
  fib <- c( 1, 1 ) 
  
  while ( fib[ length( fib ) ] < limit ) {
    last_fib <- fib[ length( fib ) ] + fib[ length( fib ) - 1 ] 
    fib <- c( fib, last_fib )
  }
  
  sum( fib[ fib %% 2 == 0 & fib < limit ] )
}

fib_even_sum( limit = 4000000 )